spring.application.name=estudantes

#Para poder subir arquivos, opcional. 
spring.servlet.multipart.enabled=true

#Tamanho maximo dos arquivos e Maximo request dentro de nosso TOMCAT
spring.servlet.multipart.max-file-size=40MB 
spring.servlet.multipart.max-request-size=40MB

#Indica aonde vai salvar os arquivos que são enviados, o ideal é fora do programa, mas estamos utilizando aqui por didatica.
spring.web.resources.static-locations=file:src/main/resources/static/,classpath:/static/